import { Product, Category, StoreSettings } from '../types';

export const INITIAL_SETTINGS: StoreSettings = {
  brandName: 'VERDANT THREADS',
  tagline: 'Artisan Custom Printed Heavyweight T-Shirts',
  heroHeading: 'WEAR YOUR CREATIVITY',
  heroDescription:
    'Heavyweight 240+ GSM combed organic cotton meets archival Japanese screen prints and tactile 3D puff designs. Built for silhouettes that command attention.',
  heroImage: '/src/assets/images/hero_tshirt_banner_1790863003479.jpg',
  promoBanner: 'SPRING 2026 DROP: COMPLIMENTARY SHIPPING ON ORDERS OVER $75 • 48H ARTISAN DISPATCH',
  showPromoBanner: true,
  contactEmail: 'studio@verdantthreads.com',
  contactPhone: '+1 (800) 837-3268',
  address: '412 Artisan Way, Fashion Design District, NY 10013',
  currency: 'USD',
  currencySymbol: '$',
  shippingFee: 6.0,
  freeShippingThreshold: 75.0,
  instagramUrl: 'https://instagram.com/verdantthreads',
  twitterUrl: 'https://twitter.com/verdantthreads',
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-printed',
    name: 'Printed T-Shirts',
    slug: 'printed-tshirts',
    description: 'High-density artistic graphic prints engineered with fade-resistant eco-inks.',
    imageUrl: '/src/assets/images/product_forest_tee_1790863018752.jpg',
    productCount: 4,
  },
  {
    id: 'cat-oversized',
    name: 'Oversized T-Shirts',
    slug: 'oversized-tshirts',
    description: 'Boxy drop-shoulder streetwear fits crafted from ultra-heavy 240-280 GSM cotton.',
    imageUrl: '/src/assets/images/product_black_tee_1790863039839.jpg',
    productCount: 4,
  },
  {
    id: 'cat-graphic',
    name: 'Graphic T-Shirts',
    slug: 'graphic-tshirts',
    description: 'Bold retro-futuristic illustrations, typography layouts, and brutalist art.',
    imageUrl: '/src/assets/images/product_sand_tee_1790863056583.jpg',
    productCount: 3,
  },
  {
    id: 'cat-custom',
    name: 'Custom T-Shirts',
    slug: 'custom-tshirts',
    description: 'Upload your own artwork or print ideas with single or bulk screen printing.',
    imageUrl: '/src/assets/images/hero_tshirt_banner_1790863003479.jpg',
    productCount: 2,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-forest-botanical',
    name: 'Botanical Blueprint Oversized Tee',
    slug: 'botanical-blueprint-oversized-tee',
    description:
      'Engineered from 260 GSM combed organic cotton in our signature deep forest emerald hue. Features a high-resolution botanical line-art study across the back with subtle minimalist coordinates on the left chest. Ribbed 1.25" neckband and double-needle stitching throughout for lifetime durability.',
    shortDescription: '260 GSM heavyweight organic cotton with archival Japanese botanical back print.',
    price: 48,
    salePrice: 42,
    sku: 'VT-BOT-01',
    category: 'Printed T-Shirts',
    images: [
      '/src/assets/images/product_forest_tee_1790863018752.jpg',
      '/src/assets/images/hero_tshirt_banner_1790863003479.jpg',
    ],
    thumbnail: '/src/assets/images/product_forest_tee_1790863018752.jpg',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Forest Emerald', code: '#173627' },
      { name: 'Washed Black', code: '#1E1E1E' },
      { name: 'Raw Cream', code: '#F5EFEB' },
    ],
    stock: 45,
    status: 'active',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    tags: ['botanical', 'oversized', 'heavyweight', 'green', 'screenprint'],
    fabricGSM: 260,
    printType: 'Archival Screen Print',
    fit: 'Boxy Oversized Fit (Drop Shoulder)',
    rating: 4.9,
    reviewsCount: 38,
    createdAt: '2026-09-15T10:00:00Z',
    updatedAt: '2026-09-15T10:00:00Z',
  },
  {
    id: 'prod-washed-vintage-black',
    name: 'Sub-Zero Vintage Acid-Wash Tee',
    slug: 'sub-zero-vintage-acid-wash-tee',
    description:
      'Hand-treated enzyme vintage wash that creates a velvety soft, worn-in patina on a 240 GSM heavy jersey base. Featuring brutalist typography and distressed monochrome screen printing across the reverse. Pre-shrunk to hold its shape through hundreds of wash cycles.',
    shortDescription: 'Vintage washed 240 GSM heavyweight black tee with distressed graphic art.',
    price: 52,
    salePrice: 45,
    sku: 'VT-VNT-02',
    category: 'Graphic T-Shirts',
    images: [
      '/src/assets/images/product_black_tee_1790863039839.jpg',
      '/src/assets/images/product_sand_tee_1790863056583.jpg',
    ],
    thumbnail: '/src/assets/images/product_black_tee_1790863039839.jpg',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Acid Washed Black', code: '#212121' },
      { name: 'Charcoal Slate', code: '#383838' },
    ],
    stock: 32,
    status: 'active',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    tags: ['vintage', 'streetwear', 'acid-wash', 'black', 'graphic'],
    fabricGSM: 240,
    printType: 'Distressed Plastisol Screen Print',
    fit: 'Relaxed Streetwear Fit',
    rating: 4.8,
    reviewsCount: 52,
    createdAt: '2026-08-20T12:00:00Z',
    updatedAt: '2026-08-20T12:00:00Z',
  },
  {
    id: 'prod-sand-puff-print',
    name: 'Tactile Terra 3D Puff-Print Tee',
    slug: 'tactile-terra-3d-puff-print-tee',
    description:
      'Elevate your wardrobe with tactile 3D raised puff printing that you can physically feel. Printed on unbleached 250 GSM French Terry cotton in an artisanal sand tone. Features high-density relief typography paired with muted olive green accents.',
    shortDescription: 'Unbleached sand 250 GSM cotton with high-density tactile 3D puff print.',
    price: 54,
    salePrice: null,
    sku: 'VT-PUF-03',
    category: 'Oversized T-Shirts',
    images: [
      '/src/assets/images/product_sand_tee_1790863056583.jpg',
      '/src/assets/images/product_forest_tee_1790863018752.jpg',
    ],
    thumbnail: '/src/assets/images/product_sand_tee_1790863056583.jpg',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Artisan Sand', code: '#E4DAC8' },
      { name: 'Forest Emerald', code: '#173627' },
      { name: 'Warm Cream', code: '#F5EFEB' },
    ],
    stock: 18,
    status: 'active',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    tags: ['puff-print', '3D', 'sand', 'oversized', 'tactile'],
    fabricGSM: 250,
    printType: '3D High-Density Puff Print',
    fit: 'Drop Shoulder Boxy',
    rating: 5.0,
    reviewsCount: 24,
    createdAt: '2026-09-01T15:30:00Z',
    updatedAt: '2026-09-01T15:30:00Z',
  },
  {
    id: 'prod-tokyo-brutalist',
    name: 'Neo-Tokyo Kanji Editorial Heavyweight Tee',
    slug: 'neo-tokyo-kanji-editorial-heavyweight-tee',
    description:
      'Striking asymmetrical typography inspired by Tokyo architectural signage and modernist poster art. Water-based discharge printing yields an exceptionally breathable, ultra-soft feel that embeds directly into the cotton fibers without heavy plastic sheen.',
    shortDescription: 'Water-based discharge typography print on 240 GSM organic ring-spun cotton.',
    price: 46,
    salePrice: 39,
    sku: 'VT-TYO-04',
    category: 'Graphic T-Shirts',
    images: [
      '/src/assets/images/product_forest_tee_1790863018752.jpg',
      '/src/assets/images/product_black_tee_1790863039839.jpg',
    ],
    thumbnail: '/src/assets/images/product_forest_tee_1790863018752.jpg',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    colors: [
      { name: 'Forest Emerald', code: '#173627' },
      { name: 'Chalk White', code: '#F8F8F8' },
      { name: 'Obsidian Black', code: '#111111' },
    ],
    stock: 28,
    status: 'active',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    tags: ['kanji', 'graphic', 'typography', 'tokyo', 'waterbased'],
    fabricGSM: 240,
    printType: 'Breathable Water-Based Discharge Print',
    fit: 'Standard Relaxed Fit',
    rating: 4.9,
    reviewsCount: 41,
    createdAt: '2026-09-10T08:00:00Z',
    updatedAt: '2026-09-10T08:00:00Z',
  },
  {
    id: 'prod-custom-studio-tee',
    name: 'Custom Studio Heavyweight Canvas Tee',
    slug: 'custom-studio-heavyweight-canvas-tee',
    description:
      'Your canvas, our artisan print workshop. Choose your exact placement (center chest, full back, left chest emblem, or sleeve cuff), upload your vector or high-resolution graphic, and let our master printers bring it to life using premium Swiss inks on 280 GSM luxury combed cotton.',
    shortDescription: 'Blank canvas for your custom artwork with front/back/sleeve placement options.',
    price: 50,
    salePrice: null,
    sku: 'VT-CUS-05',
    category: 'Custom T-Shirts',
    images: [
      '/src/assets/images/hero_tshirt_banner_1790863003479.jpg',
      '/src/assets/images/product_sand_tee_1790863056583.jpg',
    ],
    thumbnail: '/src/assets/images/hero_tshirt_banner_1790863003479.jpg',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    colors: [
      { name: 'Raw Cream', code: '#F5EFEB' },
      { name: 'Forest Emerald', code: '#173627' },
      { name: 'Washed Black', code: '#1E1E1E' },
      { name: 'Artisan Sand', code: '#E4DAC8' },
    ],
    stock: 100,
    status: 'active',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    tags: ['custom', 'custom-print', 'upload-art', 'personalized', 'heavyweight'],
    fabricGSM: 280,
    printType: 'Custom Screen / DTG Hybrid Print',
    fit: 'Heavyweight Classic Boxy Fit',
    rating: 5.0,
    reviewsCount: 89,
    createdAt: '2026-07-01T09:00:00Z',
    updatedAt: '2026-07-01T09:00:00Z',
  },
  {
    id: 'prod-retro-sun-graphic',
    name: 'Equinox Sunbeam Oversized Graphic Tee',
    slug: 'equinox-sunbeam-oversized-graphic-tee',
    description:
      'An ode to solar equinoxes, blending earthy mustard, terracotta, and deep forest hues. Printed on our softest 230 GSM organic ring-spun cotton. Pre-washed with silicone enzyme bath for an impossibly buttery drape.',
    shortDescription: 'Artistic multi-color solar artwork screen printed on butter-soft combed cotton.',
    price: 45,
    salePrice: 38,
    sku: 'VT-SUN-06',
    category: 'Printed T-Shirts',
    images: [
      '/src/assets/images/product_sand_tee_1790863056583.jpg',
      '/src/assets/images/product_forest_tee_1790863018752.jpg',
    ],
    thumbnail: '/src/assets/images/product_sand_tee_1790863056583.jpg',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Artisan Sand', code: '#E4DAC8' },
      { name: 'Forest Emerald', code: '#173627' },
      { name: 'Washed Black', code: '#1E1E1E' },
    ],
    stock: 22,
    status: 'active',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    tags: ['retro', 'sunbeam', 'earthy', 'graphic', 'oversized'],
    fabricGSM: 230,
    printType: '4-Color Precision Screen Print',
    fit: 'Relaxed Drop Shoulder',
    rating: 4.7,
    reviewsCount: 19,
    createdAt: '2026-09-18T14:00:00Z',
    updatedAt: '2026-09-18T14:00:00Z',
  },
];
