import { Product, Category, StoreSettings } from '../types';

export const INITIAL_SETTINGS: StoreSettings = {
  brandName: 'HA CLOTHING',
  tagline: 'Premium Heavyweight Streetwear & Custom Printed T-Shirts',
  logoUrl: '/images/ha_clothing_logo.jpg',
  faviconUrl: '/images/ha_clothing_logo.jpg',
  heroHeading: 'WEAR YOUR CREATIVITY',
  heroDescription:
    'Heavyweight 240+ GSM combed organic cotton meets archival Japanese screen prints and tactile 3D puff designs. Engineered for enduring structure across Pakistan.',
  heroImage: '/images/hero_tshirt_banner_1790863003479.jpg',
  promoBanner: 'SPRING 2026 DROP: COMPLIMENTARY EXPRESS DELIVERY ON ORDERS OVER RS. 5,000 • CASH ON DELIVERY NATIONWIDE',
  showPromoBanner: true,
  contactEmail: 'support@haclothing.com',
  contactPhone: '0310 1284712',
  businessEmail: 'support@haclothing.com',
  businessPhone: '0310 1284712',
  whatsappNumber: '+92 310 1284712',
  businessAddress: 'Hammad and Ayaan Apparel Studio, Fashion Ave, Lahore, Pakistan',
  supportEmail: 'orders@haclothing.com',
  supportPhone: '0310 1284712',
  address: 'Hammad and Ayaan Studio, Fashion Ave, Lahore, Pakistan',
  currency: 'PKR',
  currencySymbol: 'Rs.',
  shippingFee: 250,
  freeShippingThreshold: 5000,
  deliveryDays: '2 - 4 business days nationwide (TCS / Leopard / Call Courier)',
  instagramUrl: 'https://instagram.com/haclothing',
  facebookUrl: 'https://facebook.com/haclothing',
  tiktokUrl: 'https://tiktok.com/@haclothing',
  twitterUrl: 'https://twitter.com/haclothing',
  footerText: 'HA Clothing — Premium Heavyweight Streetwear. Designed & manufactured with artisanal precision in Pakistan.',
  styleInspirationTitle: 'Style Inspiration',
  styleInspirationSubtitle: 'Athletic Dominance Meets Contemporary Street Silhouette',
  styleInspirationAthlete1Name: 'Babar Azam',
  styleInspirationAthlete1Role: 'Modern Cricket Icon & Streetwear Pioneer',
  styleInspirationAthlete1Image: '/images/babar_azam.jpg',
  styleInspirationAthlete2Name: 'Virat Kohli',
  styleInspirationAthlete2Role: 'Global Sporting Phenomenon & Athleisure Influence',
  styleInspirationAthlete2Image: '/images/virat_kohli.jpg',
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-printed',
    name: 'Printed T-Shirts',
    slug: 'printed-tshirts',
    description: 'High-density artistic graphic prints engineered with fade-resistant eco-inks.',
    imageUrl: '/images/product_forest_tee_1790863018752.jpg',
    productCount: 4,
  },
  {
    id: 'cat-oversized',
    name: 'Oversized T-Shirts',
    slug: 'oversized-tshirts',
    description: 'Boxy drop-shoulder streetwear fits crafted from ultra-heavy 240-280 GSM cotton.',
    imageUrl: '/images/product_black_tee_1790863039839.jpg',
    productCount: 4,
  },
  {
    id: 'cat-graphic',
    name: 'Graphic T-Shirts',
    slug: 'graphic-tshirts',
    description: 'Bold retro-futuristic illustrations, typography layouts, and brutalist art.',
    imageUrl: '/images/product_sand_tee_1790863056583.jpg',
    productCount: 3,
  },
  {
    id: 'cat-custom',
    name: 'Custom T-Shirts',
    slug: 'custom-tshirts',
    description: 'Upload your own artwork or print ideas with single or bulk screen printing.',
    imageUrl: '/images/hero_tshirt_banner_1790863003479.jpg',
    productCount: 2,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-forest-botanical',
    name: 'Botanical Blueprint Oversized Tee',
    slug: 'botanical-blueprint-oversized-tee',
    description:
      'Engineered from 260 GSM combed organic cotton in our signature deep forest emerald hue. Features a high-resolution botanical line-art study across the back with subtle minimalist coordinates on the left chest. Ribbed 1.25" neckband and double-needle stitching throughout for lifetime durability.',
    shortDescription: '260 GSM heavyweight organic cotton with archival Japanese botanical back print.',
    price: 3499,
    salePrice: 2999,
    sku: 'HA-BOT-01',
    category: 'Printed T-Shirts',
    images: [
      '/images/product_forest_tee_1790863018752.jpg',
      '/images/hero_tshirt_banner_1790863003479.jpg',
    ],
    thumbnail: '/images/product_forest_tee_1790863018752.jpg',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Forest Emerald', code: '#173627' },
      { name: 'Washed Black', code: '#1E1E1E' },
      { name: 'Raw Cream', code: '#F5EFEB' },
    ],
    stock: 45,
    status: 'active',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    tags: ['botanical', 'oversized', 'heavyweight', 'green', 'screenprint'],
    fabricGSM: 260,
    printType: 'Archival Screen Print',
    fit: 'Boxy Oversized Fit (Drop Shoulder)',
    rating: 4.9,
    reviewsCount: 38,
    createdAt: '2026-09-15T10:00:00Z',
    updatedAt: '2026-09-15T10:00:00Z',
  },
  {
    id: 'prod-washed-vintage-black',
    name: 'Sub-Zero Vintage Acid-Wash Tee',
    slug: 'sub-zero-vintage-acid-wash-tee',
    description:
      'Hand-treated enzyme vintage wash that creates a velvety soft, worn-in patina on a 240 GSM heavy jersey base. Featuring brutalist typography and distressed monochrome screen printing across the reverse. Pre-shrunk to hold its shape through hundreds of wash cycles.',
    shortDescription: 'Vintage washed 240 GSM heavyweight black tee with distressed graphic art.',
    price: 3899,
    salePrice: 3299,
    sku: 'HA-VNT-02',
    category: 'Graphic T-Shirts',
    images: [
      '/images/product_black_tee_1790863039839.jpg',
      '/images/product_sand_tee_1790863056583.jpg',
    ],
    thumbnail: '/images/product_black_tee_1790863039839.jpg',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Acid Washed Black', code: '#212121' },
      { name: 'Charcoal Slate', code: '#383838' },
    ],
    stock: 32,
    status: 'active',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    tags: ['vintage', 'streetwear', 'acid-wash', 'black', 'graphic'],
    fabricGSM: 240,
    printType: 'Distressed Plastisol Screen Print',
    fit: 'Relaxed Streetwear Fit',
    rating: 4.8,
    reviewsCount: 52,
    createdAt: '2026-08-20T12:00:00Z',
    updatedAt: '2026-08-20T12:00:00Z',
  },
  {
    id: 'prod-sand-puff-print',
    name: 'Tactile Terra 3D Puff-Print Tee',
    slug: 'tactile-terra-3d-puff-print-tee',
    description:
      'Elevate your wardrobe with tactile 3D raised puff printing that you can physically feel. Printed on unbleached 250 GSM French Terry cotton in an artisanal sand tone. Features high-density relief typography paired with muted olive green accents.',
    shortDescription: 'Unbleached sand 250 GSM cotton with high-density tactile 3D puff print.',
    price: 3699,
    salePrice: null,
    sku: 'HA-PUF-03',
    category: 'Oversized T-Shirts',
    images: [
      '/images/product_sand_tee_1790863056583.jpg',
      '/images/product_forest_tee_1790863018752.jpg',
    ],
    thumbnail: '/images/product_sand_tee_1790863056583.jpg',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Artisan Sand', code: '#E4DAC8' },
      { name: 'Forest Emerald', code: '#173627' },
      { name: 'Warm Cream', code: '#F5EFEB' },
    ],
    stock: 18,
    status: 'active',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    tags: ['puff-print', '3D', 'sand', 'oversized', 'tactile'],
    fabricGSM: 250,
    printType: '3D High-Density Puff Print',
    fit: 'Drop Shoulder Boxy',
    rating: 5.0,
    reviewsCount: 24,
    createdAt: '2026-09-01T15:30:00Z',
    updatedAt: '2026-09-01T15:30:00Z',
  },
  {
    id: 'prod-tokyo-brutalist',
    name: 'Neo-Tokyo Kanji Editorial Heavyweight Tee',
    slug: 'neo-tokyo-kanji-editorial-heavyweight-tee',
    description:
      'Striking asymmetrical typography inspired by Tokyo architectural signage and modernist poster art. Water-based discharge printing yields an exceptionally breathable, ultra-soft feel that embeds directly into the cotton fibers without heavy plastic sheen.',
    shortDescription: 'Water-based discharge typography print on 240 GSM organic ring-spun cotton.',
    price: 3199,
    salePrice: 2699,
    sku: 'HA-TYO-04',
    category: 'Graphic T-Shirts',
    images: [
      '/images/product_forest_tee_1790863018752.jpg',
      '/images/product_black_tee_1790863039839.jpg',
    ],
    thumbnail: '/images/product_forest_tee_1790863018752.jpg',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    colors: [
      { name: 'Forest Emerald', code: '#173627' },
      { name: 'Chalk White', code: '#F8F8F8' },
      { name: 'Obsidian Black', code: '#111111' },
    ],
    stock: 28,
    status: 'active',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    tags: ['kanji', 'graphic', 'typography', 'tokyo', 'waterbased'],
    fabricGSM: 240,
    printType: 'Breathable Water-Based Discharge Print',
    fit: 'Standard Relaxed Fit',
    rating: 4.9,
    reviewsCount: 41,
    createdAt: '2026-09-10T08:00:00Z',
    updatedAt: '2026-09-10T08:00:00Z',
  },
  {
    id: 'prod-custom-studio-tee',
    name: 'Custom Studio Heavyweight Canvas Tee',
    slug: 'custom-studio-heavyweight-canvas-tee',
    description:
      'Your canvas, our artisan print workshop. Choose your exact placement (center chest, full back, left chest emblem, or sleeve cuff), upload your vector or high-resolution graphic, and let our master printers bring it to life using premium Swiss inks on 280 GSM luxury combed cotton.',
    shortDescription: 'Blank canvas for your custom artwork with front/back/sleeve placement options.',
    price: 3499,
    salePrice: null,
    sku: 'HA-CUS-05',
    category: 'Custom T-Shirts',
    images: [
      '/images/hero_tshirt_banner_1790863003479.jpg',
      '/images/product_sand_tee_1790863056583.jpg',
    ],
    thumbnail: '/images/hero_tshirt_banner_1790863003479.jpg',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    colors: [
      { name: 'Raw Cream', code: '#F5EFEB' },
      { name: 'Forest Emerald', code: '#173627' },
      { name: 'Washed Black', code: '#1E1E1E' },
      { name: 'Artisan Sand', code: '#E4DAC8' },
    ],
    stock: 100,
    status: 'active',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    tags: ['custom', 'custom-print', 'upload-art', 'personalized', 'heavyweight'],
    fabricGSM: 280,
    printType: 'Custom Screen / DTG Hybrid Print',
    fit: 'Heavyweight Classic Boxy Fit',
    rating: 5.0,
    reviewsCount: 89,
    createdAt: '2026-07-01T09:00:00Z',
    updatedAt: '2026-07-01T09:00:00Z',
  },
  {
    id: 'prod-retro-sun-graphic',
    name: 'Equinox Sunbeam Oversized Graphic Tee',
    slug: 'equinox-sunbeam-oversized-graphic-tee',
    description:
      'An ode to solar equinoxes, blending earthy mustard, terracotta, and deep forest hues. Printed on our softest 230 GSM organic ring-spun cotton. Pre-washed with silicone enzyme bath for an impossibly buttery drape.',
    shortDescription: 'Artistic multi-color solar artwork screen printed on butter-soft combed cotton.',
    price: 2999,
    salePrice: 2499,
    sku: 'HA-SUN-06',
    category: 'Printed T-Shirts',
    images: [
      '/images/product_sand_tee_1790863056583.jpg',
      '/images/product_forest_tee_1790863018752.jpg',
    ],
    thumbnail: '/images/product_sand_tee_1790863056583.jpg',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Artisan Sand', code: '#E4DAC8' },
      { name: 'Forest Emerald', code: '#173627' },
      { name: 'Washed Black', code: '#1E1E1E' },
    ],
    stock: 22,
    status: 'active',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    tags: ['retro', 'sunbeam', 'earthy', 'graphic', 'oversized'],
    fabricGSM: 230,
    printType: '4-Color Precision Screen Print',
    fit: 'Relaxed Drop Shoulder',
    rating: 4.7,
    reviewsCount: 19,
    createdAt: '2026-09-18T14:00:00Z',
    updatedAt: '2026-09-18T14:00:00Z',
  },
];
